version: 1.0.{build}
  configuration: Release
platform: Any CPU
install:
  - cmd: nuget sources add -Name SitecorePublicFeed -Source https://sitecore.myget.org/F/sc-packages/api/v3/index.json
before_build:
  - cmd: nuget restore src\SitecoreGadgets.SitecoreRollingFileAppender.sln
build:
  verbosity: normal
deploy:
  release: SitecoreRollingLogFileAppender-v$(appveyor_build_version)
  description: 'log4net rolling log file appender for Sitecore'
  provider: GitHub
  auth_token:
    secure: TJ/Yref6RnJKEmAFwqG6wKbR2dE8hweC4GBlpOPLsAmVBLXDiomOGz4SNujxoK2f
  artifact: /.*\.nupkg/
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true